INSERT INTO public.services (slug, name, code, tagline, description, benefits, body, sort_order) VALUES
('seo','SEO','S','Compounding organic demand','Technical SEO, keyword strategy, content optimization and organic growth.',ARRAY['Technical crawl & Core Web Vitals fixes','Keyword and intent mapping','Content optimization at scale','Authority and link acquisition'],'We treat organic search as an engine, not a checklist. Every engagement starts with a technical audit and an intent map, then moves into a publishing and optimization cadence tied to pipeline — not to rankings alone.',1),
('google-ads','Google Ads','A','Paid search that pays back','Search, display, remarketing and conversion-focused paid campaigns.',ARRAY['Account restructure around intent','Conversion tracking you can trust','Remarketing and audience layering','Budget pacing and bid strategy testing'],'Most paid accounts leak budget through loose match types, untracked conversions and unsegmented audiences. We rebuild the account around commercial intent, then optimise to cost per qualified lead.',2),
('social-media-marketing','Social Media Marketing','S','Attention with a measurable floor','Strategy, content, paid social and measurable community growth.',ARRAY['Channel-specific content systems','Paid social testing frameworks','Creator and community programs','Creative performance reporting'],'Social works when creative volume meets a measurement loop. We build both: a repeatable content system and a paid testing framework that promotes what actually converts.',3),
('content-marketing','Content Marketing','C','Copy that carries the funnel','SEO content, landing pages, blogs and conversion copy.',ARRAY['Editorial strategy tied to keywords','Landing page and offer copy','Sales enablement assets','Conversion copy testing'],'Content briefs are written from search intent and sales objections, not from topic lists. Every asset has a job in the funnel and a metric attached to it.',4),
('web-development','Web Development','W','Fast sites that rank and convert','High-performance marketing websites and landing pages.',ARRAY['Core Web Vitals-first builds','Modular landing page systems','Analytics and consent wiring','CMS-backed content operations'],'We build marketing sites the way product teams build apps: componentised, measurable, and fast by default so paid and organic traffic is not wasted on slow pages.',5),
('email-marketing','Email Marketing','E','Nurture that compounds','Lead nurturing, automation and conversion campaigns.',ARRAY['Lifecycle and nurture flows','Segmentation and list hygiene','Deliverability improvements','Revenue attribution per flow'],'Email is where lead generation becomes revenue. We map lifecycle stages, build the flows, and report on revenue per send instead of open rates.',6),
('branding','Branding','B','Positioning that makes traction stick','Brand identity, positioning and digital brand systems.',ARRAY['Positioning and messaging platform','Visual identity systems','Design tokens and UI kits','Brand governance docs'],'Performance marketing plateaus without positioning. We define the category story and build the design system that makes every campaign feel like it came from one company.',7);

INSERT INTO public.case_studies (slug, client_name, industry, headline, challenge, strategy, services_used, metrics_before, metrics_after, growth_percentage, headline_metric, duration, testimonial, testimonial_author, is_demo, sort_order) VALUES
('b2b-saas-pipeline','Sample Client A (Demo)','B2B SaaS','Rebuilding a paid funnel around qualified pipeline','Paid spend was growing while qualified demo requests stayed flat. Tracking counted every form fill as a conversion, so bidding optimised toward low-intent traffic.','We rebuilt conversion tracking around qualified opportunities, restructured campaigns by intent tier, and shipped three new landing page variants with a tighter offer.',ARRAY['Google Ads','Web Development','Content Marketing'],'{"leads":142,"cpl":"$186","conv_rate":"1.4%"}'::jsonb,'{"leads":584,"cpl":"$74","conv_rate":"4.2%"}'::jsonb,312,'+312% qualified leads','6 months','The reporting finally matched what our sales team was seeing. That alone changed how we spend.','Head of Growth, Sample Client A',true,1),
('ecommerce-roas','Sample Client B (Demo)','E-commerce','Cutting wasted spend without losing volume','Blended ROAS had slipped below break-even during a scale-up, with heavy overlap between prospecting and remarketing audiences.','Audience exclusions, creative rotation by funnel stage, and a feed cleanup, paired with a post-purchase email flow to lift lifetime value.',ARRAY['Google Ads','Social Media Marketing','Email Marketing'],'{"roas":"2.1x","cac":"$61","aov":"$88"}'::jsonb,'{"roas":"5.3x","cac":"$34","aov":"$91"}'::jsonb,152,'5.3x ROAS','4 months','We spend less and sell more. The audience overlap fix was worth the entire engagement.','Founder, Sample Client B',true,2),
('fintech-organic','Sample Client C (Demo)','Fintech','An organic engine built on intent, not volume','The blog attracted traffic that never converted. Technical debt kept new pages out of the index for weeks.','Technical remediation, an intent-mapped content plan targeting comparison and alternative queries, and internal linking built around money pages.',ARRAY['SEO','Content Marketing'],'{"organic_sessions":18400,"organic_leads":36}'::jsonb,'{"organic_sessions":52900,"organic_leads":214}'::jsonb,494,'+494% organic leads','9 months','Organic went from a vanity channel to our second-best source of pipeline.','CMO, Sample Client C',true,3),
('healthcare-local','Sample Client D (Demo)','Healthcare','Local demand capture across 12 locations','Location pages competed with each other and paid campaigns pointed everyone at one generic booking form.','A location page architecture with unique content and schema, geo-segmented paid campaigns, and per-location booking tracking.',ARRAY['SEO','Google Ads','Web Development'],'{"bookings":310,"cpl":"$44"}'::jsonb,'{"bookings":905,"cpl":"$27"}'::jsonb,192,'+192% bookings','7 months','Every location now has its own numbers, so we can invest where it works.','Marketing Director, Sample Client D',true,4),
('b2b-services-brand','Sample Client E (Demo)','Professional Services','Positioning first, performance second','Strong delivery, weak differentiation. Every proposal turned into a price conversation.','A repositioning sprint, a new messaging platform and design system, then paid and content rollout against the new category story.',ARRAY['Branding','Content Marketing','Web Development'],'{"win_rate":"18%","avg_deal":"$14k"}'::jsonb,'{"win_rate":"31%","avg_deal":"$23k"}'::jsonb,72,'+72% average deal size','5 months','We stopped competing on price the moment our positioning got specific.','Managing Partner, Sample Client E',true,5);

INSERT INTO public.blog_posts (slug, title, excerpt, content, author, category, tags, featured, published_at, seo_title, seo_description) VALUES
('conversion-tracking-you-can-trust','Conversion Tracking You Can Actually Trust','If your bidding algorithm optimises toward the wrong event, more budget just buys more of the wrong traffic.','Conversion tracking is the single highest-leverage thing in a paid account, and it is almost always the least maintained. Start by separating form fills from qualified opportunities. Feed the qualified event back into the platform, keep the raw form fill as a secondary signal, and reconcile against your CRM monthly. Everything downstream — bidding, budget allocation, creative decisions — inherits the quality of that one definition.','Priya Raman','Paid Media',ARRAY['analytics','google ads','attribution'],true,now() - interval '3 days','Conversion Tracking You Can Actually Trust','How to define, wire and reconcile conversion events so paid bidding optimises toward real pipeline.'),
('utm-attribution-that-survives','UTM Attribution That Survives the Whole Funnel','Attribution breaks in the gap between the first click and the CRM record. Persist it deliberately.','Most attribution loss happens because UTM parameters are read once, on the landing page, and then discarded during navigation. Capture them on first touch, persist them for the session, and attach them to every lead record and analytics event. Store landing page and referrer alongside them — those two fields answer more questions than any dashboard.','Marcus Whyte','Analytics',ARRAY['utm','attribution','analytics'],false,now() - interval '9 days','UTM Attribution That Survives the Whole Funnel','A practical pattern for capturing, persisting and storing UTM attribution through to your CRM.'),
('technical-seo-audit-checklist','The Technical SEO Audit That Finds Real Money','Most audits produce 200 issues and no priority. Here is how we rank them by revenue impact.','A useful audit ends with three lists: things blocking indexation, things slowing the page, and things diluting relevance. Fix indexation first — nothing else matters if the page cannot be crawled. Then Core Web Vitals, because they affect both ranking and conversion. Relevance work comes last but compounds the longest.','Ana Duarte','SEO',ARRAY['seo','technical','audit'],false,now() - interval '15 days','The Technical SEO Audit That Finds Real Money','Prioritise technical SEO work by revenue impact instead of shipping a 200-item issue list.'),
('landing-pages-that-convert','Landing Pages That Convert Paid Traffic','Message match, one decision, and proof placed where the objection appears.','A landing page has one job: continue the conversation the ad started. Match the headline to the query, remove every navigation path that is not the conversion, and place proof next to the specific objection it answers rather than in a testimonial carousel at the bottom. Then test the offer before you test the button colour.','Priya Raman','CRO',ARRAY['cro','landing pages','paid media'],false,now() - interval '21 days','Landing Pages That Convert Paid Traffic','Structural landing page decisions that move conversion rate more than cosmetic testing.'),
('cost-per-lead-is-not-enough','Cost Per Lead Is Not Enough','Optimising CPL without qualification data is how accounts get cheaper and worse at the same time.','Cost per lead is a useful denominator only when the numerator is consistent. Add a qualification stage to your reporting and track cost per qualified lead alongside CPL. When the two diverge, you have found a targeting or offer problem — not a bidding problem.','Marcus Whyte','Growth',ARRAY['metrics','paid media','reporting'],false,now() - interval '28 days','Cost Per Lead Is Not Enough','Why cost per qualified lead should replace CPL as your primary paid media metric.'),
('email-flows-worth-building','The Five Email Flows Worth Building First','Before campaigns, build the flows. They run without you and compound quietly.','Welcome, lead nurture, abandoned intent, post-purchase and win-back. Those five cover the majority of lifecycle revenue for most businesses. Build them with segmentation from day one, then measure revenue per recipient rather than open rate.','Ana Duarte','Email',ARRAY['email','lifecycle','automation'],false,now() - interval '34 days','The Five Email Flows Worth Building First','A prioritised order for building lifecycle email automation that generates revenue.'),
('creative-testing-framework','A Creative Testing Framework for Paid Social','Volume without structure is noise. Structure without volume is slow. You need both.','Define your variables before you launch: hook, format, proof and offer. Test one variable per cohort, hold budget steady long enough to clear the learning phase, and archive winners into a reusable creative library. The library is the actual asset — not any single ad.','Priya Raman','Social',ARRAY['paid social','creative','testing'],false,now() - interval '41 days','A Creative Testing Framework for Paid Social','How to structure paid social creative testing so results are readable and reusable.'),
('marketing-site-performance','Your Marketing Site Speed Is a Media Cost','Every second of load time is budget you already paid for and did not receive.','Slow pages waste paid clicks and suppress organic rankings simultaneously. Treat Core Web Vitals as a media efficiency metric: measure it on the pages that receive spend, fix layout shift and image weight first, and re-measure after each release rather than quarterly.','Marcus Whyte','Web',ARRAY['performance','web vitals','seo'],false,now() - interval '48 days','Your Marketing Site Speed Is a Media Cost','Framing site performance as media efficiency, and the fixes that matter most.');

INSERT INTO public.campaigns (slug, name, headline, description, cta_label, cta_variant_b_label, target_audience, utm_campaign, status, start_date, end_date) VALUES
('saas-growth-audit','SaaS Growth Audit','Your paid funnel is leaking qualified pipeline.','A focused audit for B2B SaaS teams spending over $10k/month: conversion tracking, campaign structure, landing page match and offer strength — reviewed in one pass.','Book Your Free Strategy Call','Get Your Free Marketing Audit','B2B SaaS marketing leaders','saas-growth-audit','active',current_date - 20,current_date + 70),
('ecommerce-roas-reset','E-commerce ROAS Reset','Spending more and earning less? Start with audience overlap.','For e-commerce teams whose blended ROAS slipped during scale-up. We review audience structure, creative rotation, feed health and post-purchase lifecycle.','Book Your Free Strategy Call','Get Your Free Marketing Audit','DTC and e-commerce operators','ecommerce-roas-reset','active',current_date - 12,current_date + 78),
('local-demand-capture','Local Demand Capture','Twelve locations, twelve sets of numbers.','A multi-location growth review covering location page architecture, local schema, geo-segmented paid campaigns and per-location conversion tracking.','Book Your Free Strategy Call','Get Your Free Marketing Audit','Multi-location service businesses','local-demand-capture','active',current_date - 5,current_date + 85);

INSERT INTO public.ab_tests (key, name, page, variant_a_label, variant_b_label, status) VALUES
('campaign_primary_cta','Campaign primary CTA wording','/campaign/[slug]','Book Your Free Strategy Call','Get Your Free Marketing Audit','running'),
('home_hero_cta','Homepage hero CTA wording','/','Book a Free Strategy Call','Get Free Marketing Audit','running');

INSERT INTO public.leads (name, business_name, email, phone, website, industry, budget, service, goal, message, form_type, status, is_demo, utm_source, utm_medium, utm_campaign, landing_page, referrer, ab_variant, created_at) VALUES
('Jordan Reyes','Northwind Logistics','jordan.reyes@example.com','+1 415 555 0142','northwind.example.com','Logistics','$10K – $25K','Google Ads','Lower cost per qualified lead','Spending heavily on search with poor lead quality.','audit','Qualified',true,'google','cpc','saas-growth-audit','/campaign/saas-growth-audit','https://www.google.com/','A',now() - interval '2 days'),
('Amara Osei','Cobalt Studio','amara@example.com','+44 20 7946 0234','cobaltstudio.example.com','Creative Services','$5K – $10K','SEO','Grow organic pipeline','Our blog gets traffic but no enquiries.','audit','New',true,'linkedin','social','saas-growth-audit','/free-audit','https://www.linkedin.com/','B',now() - interval '3 days'),
('Tom Bright','Halden Health','tom.bright@example.com','+1 212 555 0198','haldenhealth.example.com','Healthcare','$25K+','Web Development','Improve booking conversion','Twelve clinics, one generic booking form.','call','Proposal',true,'google','organic','','/book-call','https://www.google.com/','A',now() - interval '4 days'),
('Sara Lind','Meridian Tools','sara.lind@example.com','+46 8 123 456','meridiantools.example.com','Manufacturing','$10K – $25K','Google Ads','Reduce wasted ad spend','Match types are too broad.','audit','Contacted',true,'bing','cpc','ecommerce-roas-reset','/campaign/ecommerce-roas-reset','https://www.bing.com/','A',now() - interval '5 days'),
('Nikhil Rao','Field & Form','nikhil@example.com','+91 22 5555 0177','fieldform.example.com','E-commerce','$5K – $10K','Social Media Marketing','Scale paid social profitably','Creative fatigue after six weeks.','audit','New',true,'instagram','paid_social','ecommerce-roas-reset','/campaign/ecommerce-roas-reset','https://www.instagram.com/','B',now() - interval '6 days'),
('Claire Dubois','Orbital Fintech','claire.dubois@example.com','+33 1 4455 6677','orbital.example.com','Fintech','$25K+','SEO','Own comparison queries','Indexation delays on new pages.','audit','Won',true,'google','organic','','/services/seo','https://www.google.com/','A',now() - interval '7 days'),
('Ben Carter','Cascara Coffee','ben@example.com','+61 2 5550 8891','cascara.example.com','Food & Beverage','$2K – $5K','Email Marketing','Increase repeat purchase','No lifecycle flows at all.','audit','Contacted',true,'newsletter','email','ecommerce-roas-reset','/free-audit',NULL,'A',now() - interval '8 days'),
('Yuki Tanaka','Kelvin Robotics','yuki.tanaka@example.com','+81 3 5555 0122','kelvin.example.com','Industrial','$10K – $25K','Content Marketing','Build technical authority','Engineers write, nobody optimises.','call','Qualified',true,'google','cpc','saas-growth-audit','/campaign/saas-growth-audit','https://www.google.com/','B',now() - interval '9 days'),
('Marta Silva','Axiom Legal','marta.silva@example.com','+351 21 555 0100','axiomlegal.example.com','Legal','$5K – $10K','Branding','Stop competing on price','Positioning is generic.','audit','Lost',true,'referral','referral','','/services/branding','https://partner.example.com/','A',now() - interval '10 days'),
('David Okonkwo','Bright Ledger','david.o@example.com','+234 1 555 0155','brightledger.example.com','Accounting','$2K – $5K','Google Ads','Predictable lead volume','Lead flow swings week to week.','audit','New',true,'google','cpc','local-demand-capture','/campaign/local-demand-capture','https://www.google.com/','A',now() - interval '11 days'),
('Elena Petrova','Vela Interiors','elena@example.com','+7 495 555 0166','velainteriors.example.com','Interior Design','$5K – $10K','Social Media Marketing','More qualified enquiries','Followers up, enquiries flat.','audit','Contacted',true,'instagram','paid_social','local-demand-capture','/campaign/local-demand-capture','https://www.instagram.com/','B',now() - interval '12 days'),
('Hugo Martin','Northbeam Solar','hugo.martin@example.com','+1 303 555 0111','northbeamsolar.example.com','Energy','$25K+','Web Development','Faster site, better ranking','Pages take five seconds to load.','call','Proposal',true,'google','organic','','/services/web-development','https://www.google.com/','A',now() - interval '13 days'),
('Priya Nair','Lumen Learning','priya.nair@example.com','+91 80 5555 0199','lumenlearning.example.com','Education','$10K – $25K','Email Marketing','Nurture trial signups','Trials go cold after day three.','audit','Qualified',true,'google','cpc','saas-growth-audit','/free-audit','https://www.google.com/','A',now() - interval '15 days'),
('Owen Walsh','Trail & Ridge','owen@example.com','+353 1 555 0144','trailridge.example.com','Outdoor Retail','$5K – $10K','Google Ads','Improve ROAS','Prospecting and remarketing overlap.','audit','New',true,'facebook','paid_social','ecommerce-roas-reset','/campaign/ecommerce-roas-reset','https://www.facebook.com/','B',now() - interval '17 days'),
('Lina Haddad','Cedar Property','lina.haddad@example.com','+971 4 555 0133','cedarproperty.example.com','Real Estate','$10K – $25K','SEO','Rank for local searches','Location pages cannibalise each other.','audit','Contacted',true,'google','organic','','/services/seo','https://www.google.com/','A',now() - interval '19 days'),
('Felix Braun','Arbor Dental','felix.braun@example.com','+49 30 5555 0188','arbordental.example.com','Healthcare','$2K – $5K','Google Ads','More bookings per clinic','Cannot attribute bookings to clinics.','call','Won',true,'google','cpc','local-demand-capture','/campaign/local-demand-capture','https://www.google.com/','A',now() - interval '21 days'),
('Rosa Alvarez','Mesa Foods','rosa@example.com','+34 91 555 0122','mesafoods.example.com','Food & Beverage','$5K – $10K','Content Marketing','Build organic demand','No content strategy in place.','audit','New',true,'linkedin','social','','/blog','https://www.linkedin.com/','B',now() - interval '24 days'),
('Ken Adeyemi','Pulse Analytics','ken.adeyemi@example.com','+1 646 555 0177','pulseanalytics.example.com','B2B SaaS','$25K+','Google Ads','Cost per qualified lead','Sales says leads are unqualified.','audit','Qualified',true,'google','cpc','saas-growth-audit','/campaign/saas-growth-audit','https://www.google.com/','A',now() - interval '27 days'),
('Ingrid Solberg','Fjord Fitness','ingrid@example.com','+47 22 555 0100','fjordfitness.example.com','Fitness','$2K – $5K','Social Media Marketing','Fill class schedules','Local awareness is low.','audit','Lost',true,'tiktok','paid_social','local-demand-capture','/campaign/local-demand-capture','https://www.tiktok.com/','B',now() - interval '31 days'),
('Samuel Grant','Ridgeline Legal','samuel.grant@example.com','+1 512 555 0121','ridgelinelegal.example.com','Legal','$10K – $25K','Branding','Reposition the firm','Every pitch becomes a price talk.','call','Proposal',true,'referral','referral','','/book-call','https://partner.example.com/','A',now() - interval '35 days');